CREATE TABLE `exportacion2017` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Id interno para la tabla',
  `GESTION` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Gestion de exportacion',
  `CATEGORIA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Categoria comprende 1=Exportacion; 2=Reexportacion; 3=Efectos personales',
  `MES` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Mes de la exportacion',
  `BIMESTRE` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Bimestre a la que corresponde la exportacion',
  `TRIMESTRE` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Trimestre a la que corresponde la exportacion',
  `CUATRIMESTRE` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Cuatrimestre a la que corresponde la exportacion',
  `SEMESTRE` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Semestre a la que corresponde la exportacion',
  `ADUANA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de aduana de salida',
  `NANDINA` char(12) NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Partida arancelaria a 10 digitos',
  `PARTIDA` char(4) NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Partida a 4 digitos',
  `SUBPARTIDA` char(6) NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Partida a 6 digitos',
  `CAPITULO` char(2) NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Capitulo del arancel a 2 digitos',
  `SECCION` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Seccion a 2 digitos',
  `PAIS` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de pais al que se exporta',
  `AREA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de area al que se exporta',
  `MEDIO` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Medio de transporte por el que se exporta',
  `VIA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Via de salida por el que se exporta',
  `DEPTO` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de departamentos componentes de Bolivia. De 1-9 y 10 no especificado',
  `CUCI` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador CUCI Clasificación Uniforme de Comercio Internacional',
  `GCE` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador GCE Grandes Categorias Economicas',
  `SECTOR` int(11) unsigned NOT NULL DEFAULT '1' COMMENT 'Sector del Clasificador Actividad Economica - categoria',
  `CODACT` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador clasificacion por Actividad Economica',
  `CIIU_SECCION` char(1) NOT NULL DEFAULT '-' COMMENT 'Clasificador CIIU seccion',
  `CIIU` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador CIIU Clasificación Industrial Internacional Uniforme',
  `TNT` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Clasificador TNT Tradicionales y No Tradicionales',
  `TNT_GRUPO` int(11) NOT NULL DEFAULT '1' COMMENT 'Clasificador TNT grupo',
  `TNT_CLASE` int(11) NOT NULL DEFAULT '1' COMMENT 'Clasificador TNT clase',
  `KILBRU` double unsigned NOT NULL DEFAULT '0' COMMENT 'Valor de los kilos brutos exportados',
  `KILNET` double unsigned NOT NULL DEFAULT '0' COMMENT 'Valor de los kilos netos exportados',
  `FINUNI` double unsigned NOT NULL DEFAULT '0' COMMENT 'Valor de los kilos finos exportados, utilizando Kilogramos para Minerales y Metros cubicos para Gas natural',
  `VALOR` double unsigned NOT NULL DEFAULT '0' COMMENT 'valor de las exportaciones expresados en dolares americanos',
  `id_anb` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'id que identifica a la empresa exportadora',
  PRIMARY KEY (`ID`),
  KEY `export_codact` (`CODACT`),
  KEY `export_nandina` (`NANDINA`) USING BTREE,
  KEY `export_nanpartida` (`PARTIDA`),
  KEY `export_nancapitulo` (`CAPITULO`),
  KEY `export_nanseccion` (`SECCION`),
  KEY `export_gce` (`GCE`) USING BTREE,
  KEY `export_ciiu` (`CIIU`) USING BTREE,
  KEY `export_pais` (`PAIS`),
  KEY `export_area` (`AREA`),
  KEY `export_medio` (`MEDIO`),
  KEY `export_via` (`VIA`),
  KEY `export_depto` (`DEPTO`),
  KEY `export_tnt` (`TNT`),
  KEY `export_ciiu_secc` (`CIIU_SECCION`) USING BTREE,
  KEY `export_tnt_grupo` (`TNT_GRUPO`),
  KEY `export_tnt_clase` (`TNT_CLASE`) USING BTREE,
  KEY `export_cuci` (`CUCI`),
  KEY `export_nansubpartida` (`SUBPARTIDA`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=64871 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED;
