CREATE TABLE `importacion1992` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Es un identificador para control interno de la tabla',
  `GESTION` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Gestion en la que se realiza una importacion',
  `MES` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Mes en la que se realiza una importacion',
  `BIMESTRE` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Bimestre al que pertenece el mes de la importacion',
  `TRIMESTRE` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Trimestre al que pertenece el mes de la importacion',
  `CUATRIMESTRE` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Cuatrimestre al que pertenece el mes de la importacion',
  `SEMESTRE` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Semestre al que pertenece el mes de la importacion',
  `ADUANA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de aduana por la cual se realiza la importacion',
  `DEPTO` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de departamento por la cual ingresa la importacion',
  `VIA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Via por la cual ingresa una importacion',
  `MEDIO` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Medio de transporte que se utiliza para una importacion',
  `PAIS` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Pais de la que ingresa una importacion',
  `AREA` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Area de la que proviene una importacion',
  `NANDINA` char(12) NOT NULL DEFAULT '0' COMMENT 'Codigo Nandina es la partida arancelaria a 10 digitos especificada en el arancel de importaciones',
  `PARTIDA` char(4) NOT NULL DEFAULT '0' COMMENT 'Codigo Partida es la partida arancelaria a 4 digitos especificada en el arancel de importaciones',
  `SUBPARTIDA` char(6) NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Partida a 6 digitos',
  `CAPITULO` char(2) NOT NULL DEFAULT '0' COMMENT 'Codigo Capitulo es la partida arancelaria a 2 digitos especificada en el arancel de importaciones',
  `SECCION` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo Seccion contiene capitulos de la partida arancelaria especificada en el arancel de importaciones',
  `GCE` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador Grandes Categorias Economicas GCE version 3',
  `CUODE_SECCION` int(11) NOT NULL DEFAULT '1' COMMENT 'Clasificador CUODE seccion',
  `CUODE` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador segun Uso o Destino Economico CUODE',
  `CIIU_SECCION` char(1) NOT NULL DEFAULT '-' COMMENT 'Clasificador CIIU seccion',
  `CIIU` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador Industrial Internacional Uniforme CIIU version 3',
  `CUCI` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador Uniforme para el Comercio Internacional CUCI version 3',
  `KILOS` double unsigned NOT NULL DEFAULT '0' COMMENT 'Kilos es el Volumen de una importacion ',
  `FRO` double unsigned NOT NULL DEFAULT '0' COMMENT 'FRO es el Valor CIF Frontera de una importacion expresado en dolares americanos',
  `FOB` double unsigned NOT NULL DEFAULT '0' COMMENT 'FOB es el Valor fob de una importacion expresado en dolares americanos',
  `ADU` double unsigned NOT NULL DEFAULT '0' COMMENT 'ADU es el Valor CIF Frontera en bolivianos de una importacion',
  `PAG` double unsigned NOT NULL DEFAULT '0' COMMENT 'PAG es el Valor del Gravamen pagado de una importacion expresado en bolivianos',
  `CS_ACUERDO` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'CS_ACUERDO es un codigo binario que expresa si con el pais de origen se tiene o no un acuerdo comercial.',
  `PORCENTAJE_GRAVAMEN` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Porcentaje de Gravamen Arancelario que esta pagando por la importacion del producto',
  `ZONA` varchar(75) NOT NULL DEFAULT 'Desconocida' COMMENT 'Zona geoeconomica',
  `OTROS` varchar(75) DEFAULT '' COMMENT 'Otra denominacion dentro de una zona geoeconomica',
  PRIMARY KEY (`ID`),
  KEY `index_aduana` (`ADUANA`) USING BTREE,
  KEY `index_depto` (`DEPTO`) USING BTREE,
  KEY `index_via` (`VIA`) USING BTREE,
  KEY `index_nandina` (`NANDINA`) USING BTREE,
  KEY `index_partida` (`PARTIDA`) USING BTREE,
  KEY `index_capitulo` (`CAPITULO`) USING BTREE,
  KEY `index_seccion` (`SECCION`) USING BTREE,
  KEY `index_gce` (`GCE`) USING BTREE,
  KEY `index_cuode` (`CUODE`) USING BTREE,
  KEY `index_ciiu` (`CIIU`) USING BTREE,
  KEY `index_cuci` (`CUCI`) USING BTREE,
  KEY `index_ciiu_secc` (`CIIU_SECCION`) USING BTREE,
  KEY `index_cuode_secc` (`CUODE_SECCION`) USING BTREE,
  KEY `export_nansubpartida` (`SUBPARTIDA`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=69688 DEFAULT CHARSET=utf8;
