CREATE TABLE `importacion2018` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Es un identificador para control interno de la tabla',
  `gestion` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Gestion en la que se realiza una importacion',
  `mes` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Mes en la que se realiza una importacion',
  `bimestre` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Bimestre al que pertenece el mes de la importacion',
  `trimestre` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Trimestre al que pertenece el mes de la importacion',
  `cuatrimestre` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Cuatrimestre al que pertenece el mes de la importacion',
  `semestre` int(10) unsigned NOT NULL DEFAULT '1' COMMENT 'Semestre al que pertenece el mes de la importacion',
  `aduana` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de aduana por la cual se realiza la importacion',
  `depto` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de departamento por la cual ingresa la importacion',
  `via` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Via por la cual ingresa una importacion',
  `medio` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Medio de transporte que se utiliza para una importacion',
  `pais` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Pais de la que ingresa una importacion',
  `area` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo de Area de la que proviene una importacion',
  `nandina` char(12) NOT NULL DEFAULT '0' COMMENT 'Codigo Nandina es la partida arancelaria a 10 digitos especificada en el arancel de importaciones',
  `partida` char(4) NOT NULL DEFAULT '0' COMMENT 'Codigo Partida es la partida arancelaria a 4 digitos especificada en el arancel de importaciones',
  `subpartida` char(6) NOT NULL DEFAULT '0' COMMENT 'Clasificador de la comunidad Andina-Partida a 6 digitos',
  `capitulo` char(2) NOT NULL DEFAULT '0' COMMENT 'Codigo Capitulo es la partida arancelaria a 2 digitos especificada en el arancel de importaciones',
  `seccion` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Codigo Seccion contiene capitulos de la partida arancelaria especificada en el arancel de importaciones',
  `gce` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador Grandes Categorias Economicas GCE version 3',
  `cuode_seccion` int(11) NOT NULL DEFAULT '1' COMMENT 'Clasificador CUODE seccion',
  `cuode` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador segun Uso o Destino Economico CUODE',
  `ciiu_seccion` char(1) NOT NULL DEFAULT '-' COMMENT 'Clasificador CIIU seccion',
  `ciiu` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador Industrial Internacional Uniforme CIIU version 3',
  `cuci` char(5) NOT NULL DEFAULT '0' COMMENT 'Clasificador Uniforme para el Comercio Internacional CUCI version 3',
  `kilos` double unsigned NOT NULL DEFAULT '0' COMMENT 'Kilos es el Volumen de una importacion ',
  `fro` double unsigned NOT NULL DEFAULT '0' COMMENT 'FRO es el Valor CIF Frontera de una importacion expresado en dolares americanos',
  `fob` double unsigned NOT NULL DEFAULT '0' COMMENT 'FOB es el Valor fob de una importacion expresado en dolares americanos',
  `adu` double unsigned NOT NULL DEFAULT '0' COMMENT 'ADU es el Valor CIF Frontera en bolivianos de una importacion',
  `pag` double unsigned DEFAULT '0' COMMENT 'PAG es el Valor del Gravamen pagado de una importacion expresado en bolivianos',
  `cs_acuerdo` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'CS_ACUERDO es un codigo binario que expresa si con el pais de origen se tiene o no un acuerdo comercial.',
  `porcentaje_gravamen` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Porcentaje de Gravamen Arancelario que esta pagando por la importacion del producto',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_aduana` (`aduana`) USING BTREE,
  KEY `index_depto` (`depto`) USING BTREE,
  KEY `index_via` (`via`) USING BTREE,
  KEY `index_nandina` (`nandina`) USING BTREE,
  KEY `index_partida` (`partida`) USING BTREE,
  KEY `index_capitulo` (`capitulo`) USING BTREE,
  KEY `index_seccion` (`seccion`) USING BTREE,
  KEY `index_gce` (`gce`) USING BTREE,
  KEY `index_cuode` (`cuode`) USING BTREE,
  KEY `index_ciiu` (`ciiu`) USING BTREE,
  KEY `index_cuci` (`cuci`) USING BTREE,
  KEY `index_ciiu_secc` (`ciiu_seccion`) USING BTREE,
  KEY `index_cuode_secc` (`cuode_seccion`) USING BTREE,
  KEY `index_nansubpartida` (`subpartida`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=455490 DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED;
