# Generated by Django 3.1 on 2020-08-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioPublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='El nombre que aparecera tal cual en la pagina', max_length=200)),
                ('jerarquia', models.IntegerField(blank=True, choices=[('1', 'Miembro'), ('2', 'Jefe'), ('3', 'Viceministro')], default='1', help_text='Elige la importancia del funcionario', max_length=15)),
                ('foto', models.FileField(help_text='Ingresa una foto del funcionario publico', null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
