# Generated by Django 3.1 on 2020-08-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariopublico',
            name='jerarquia',
            field=models.IntegerField(blank=True, choices=[('1', 'Miembro'), ('2', 'Jefe'), ('3', 'Viceministro')], default='1', help_text='Elige la importancia del funcionario'),
        ),
    ]
