# Generated by Django 3.1 on 2020-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_auto_20200823_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariopublico',
            name='jerarquia',
            field=models.IntegerField(blank=True, choices=[('m', 'Miembro'), ('j', 'Jefe'), ('v', 'Viceministro')], default='1', help_text='Elige la importancia del funcionario'),
        ),
    ]
