# Generated by Django 3.1 on 2020-08-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_auto_20200823_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariopublico',
            name='jerarquia',
            field=models.IntegerField(choices=[(0, 'Miembro'), (1, 'Jefe'), (2, 'Viceministro')]),
        ),
    ]
