# Generated by Django 3.1 on 2020-08-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_auto_20200823_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariopublico',
            name='cargo',
            field=models.CharField(default='miembro', help_text='El cargo aparecera tal cual en la pagina', max_length=200),
        ),
    ]
