# Generated by Django 3.1 on 2020-08-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_funcionariopublico_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='El texto aparecera tal cual en la pagina', max_length=1000)),
                ('secciones', models.IntegerField(choices=[(0, '¿Quienes Somos?'), (1, 'Mision'), (2, 'Objetivos')])),
            ],
        ),
    ]
