# Generated by Django 3.1 on 2020-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariopublico',
            name='jerarquia',
        ),
        migrations.AddField(
            model_name='funcionariopublico',
            name='nivel',
            field=models.CharField(choices=[('N1', 'NIVEL 1'), ('N2', 'NIVEL 2'), ('N3', 'NIVEL 3')], default='N3', help_text='Selecciona el nivel en que se ubicara en la pagina', max_length=2),
        ),
    ]
