# Generated by Django 3.1 on 2020-08-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_auto_20200827_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionariopublico',
            options={'verbose_name': 'Funcionario Público', 'verbose_name_plural': 'Funcionarios Públicos'},
        ),
    ]
