# Generated by Django 3.1 on 2020-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0008_auto_20200831_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='secciones',
            field=models.IntegerField(choices=[(0, '¿Quienes Somos?'), (1, 'Mision'), (2, 'Objetivos'), (3, 'ORGANIZACIÓN')]),
        ),
    ]
